export const ADD = 'ADD'
export const ADD_CART = 'ADD_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const POPULATE_STORE = 'POPULATE_STORE'
export const CREATE_FILTER_OBJECT = 'CREATE_FILTER_OBJECT '
